// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD133PS7AcSA-Rlg1yij-YiauLCpjrEmd8',
    appId: '1:1068223919146:web:41d3c3ad916f226667ff53',
    messagingSenderId: '1068223919146',
    projectId: 'baxshin-b091a',
    authDomain: 'baxshin-b091a.firebaseapp.com',
    storageBucket: 'baxshin-b091a.appspot.com',
    measurementId: 'G-79PJBH7ZEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbn04UaB4PLP9HTVH8jXExb_FDAoVIyuI',
    appId: '1:1068223919146:android:55e0c1d793d9b0f467ff53',
    messagingSenderId: '1068223919146',
    projectId: 'baxshin-b091a',
    storageBucket: 'baxshin-b091a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8VPiH_XQk6fpN38UwZKNDMgmaPZtbyA',
    appId: '1:1068223919146:ios:b2b0412be01f11c467ff53',
    messagingSenderId: '1068223919146',
    projectId: 'baxshin-b091a',
    storageBucket: 'baxshin-b091a.appspot.com',
    iosClientId: '1068223919146-fttvve5jq1su1cop5kn3ksoanfd89se8.apps.googleusercontent.com',
    iosBundleId: 'com.baxshin.app',
  );
}
